ClassProject/FitnessTracker/FitnessTracker/Controllers/RunDatasController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using FitnessTracker.Models;

namespace FitnessTracker.Controllers
{
    public class RunDatasController : Controller
    {
        private FitnessContext db = new FitnessContext();

        // GET: RunDatas
        public ActionResult Index()
        {
            var runDatas = db.RunDatas.Include(r => r.Athlete);
            return View(runDatas.ToList());
        }

        // GET: RunDatas/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            RunData runData = db.RunDatas.Find(id);
            if (runData == null)
            {
                return HttpNotFound();
            }
            return View(runData);
        }

        // GET: RunDatas/Create
        public ActionResult Create()
        {
            ViewBag.AthleteID = new SelectList(db.Athletes, "ID", "FirstName");
            return View();
        }

        // POST: RunDatas/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "RunID,AthleteID,Distance,RunTime,HeartRate,StepsPMin")] RunData runData)
        {
            if (ModelState.IsValid)
            {
                db.RunDatas.Add(runData);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.AthleteID = new SelectList(db.Athletes, "ID", "FirstName", runData.AthleteID);
            return View(runData);
        }

        // GET: RunDatas/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            RunData runData = db.RunDatas.Find(id);
            if (runData == null)
            {
                return HttpNotFound();
            }
            ViewBag.AthleteID = new SelectList(db.Athletes, "ID", "FirstName", runData.AthleteID);
            return View(runData);
        }

        // POST: RunDatas/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "RunID,AthleteID,Distance,RunTime,HeartRate,StepsPMin")] RunData runData)
        {
            if (ModelState.IsValid)
            {
                db.Entry(runData).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.AthleteID = new SelectList(db.Athletes, "ID", "FirstName", runData.AthleteID);
            return View(runData);
        }

        // GET: RunDatas/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            RunData runData = db.RunDatas.Find(id);
            if (runData == null)
            {
                return HttpNotFound();
            }
            return View(runData);
        }

        // POST: RunDatas/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            RunData runData = db.RunDatas.Find(id);
            db.RunDatas.Remove(runData);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

ClassProject/FitnessTracker/FitnessTracker/Controllers/UsersController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace FitnessTracker.Controllers
{
    public class UsersController : Controller
    {
        // GET: Users
        public ActionResult Coach()
        {
            return View();
        }

        [HttpPost]
        public ActionResult FileUpload(IEnumerable<HttpPostedFileBase> selectedFiles) {
           /* foreach (var file in selectedFiles)
            {
                Save to db code here...
            }
            */
            return Json("file uploaded successfully");
        }
    }
}

ClassProject/FitnessTracker/FitnessTracker/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
    @RenderSection("CustomStyle", false)
</head>
<body>


    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Fitness Tracker", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Home", "Index", "Home")</li>
                    <li>@Html.ActionLink("About", "About", "Home")</li>
                    <li>@Html.ActionLink("Coaches", "Coach", "Users")</li>
                    <li>@Html.ActionLink("Runs", "Index", "RunDatas")</li>
                    <li>@Html.ActionLink("Athletes", "AthleteList", "Athletes")</li>
                        
                    

                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        @RenderSection("Javascript", required: false)
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - DireDog</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>